### PR TITLE
Add link to reference documentation

### PR DESCRIPTION
**Pull request by Leo-Ryu**
Hi there!

My name is Leo, a CS student at Brown building an automated platform for editable codebase documentation.

I generated documentation for this repository and placed a link in the README. Please feel free to try it out and let me know what you think!

### CODE REVIEW

**Comment by BitTheByte** [comment]
Hello @Leo-Ryu 

Thanks for your time and efforts. I only see the reference for the docs with no newly generated docs. could you please double-check?

Thanks

**Comment by Leo-Ryu** [comment]
Hi @BitTheByte -- I'm migrating over the Get Started doc and README now-- is there anything else you'd like to have in the docs? I'll be sure to tailor them to your needs

**Comment by BitTheByte** [comment]
Hi @Leo-Ryu. If you had the time, it would be useful to add some gifs or a video demonstrating the written steps. Also I'd love to see the README.md splitted to sections. I really appreciate your efforts. thanks!

**Comment by Leo-Ryu** [comment]
@BitTheByte I've migrated over the static README and Get Started markdown files https://docs.contour.so/BitTheByte/Monitorizer/README

I'll get started on making gifs of the slack instructions, but is this good enough to merge in so other contributors can easily see/learn?

**Comment by BitTheByte** [comment]
@Leo-Ryu it looks good *enough for now*. thanks for your collaboration!

**Comment by TimothyWang56** [comment]
@BitTheByte
Hi there, and happy holidays! I'm Tim, a student at Brown University, working on this documentation platform with @Leo-Ryu. We're really interested in improving the platform and building it out based on user-feedback, and would appreciate any feedback you might have after having it merged in for a little over a week. Feel free to reach out with any thoughts/critiques!

**Pull request merged**
